language: java

jdk:
  - openjdk8

services: 
  - mysql
before_script:
- mysql -u root -e "DROP SCHEMA IF EXISTS videoclubbd;"
- mysql -u root -e "DROP USER IF EXISTS 'root'@'localhost';"
- mysql -u root -e "CREATE SCHEMA videoclubbd;"
- mysql -u root -e "CREATE USER IF NOT EXISTS 'root'@'localhost' IDENTIFIED BY 'root';"
- mysql -u root -e "GRANT ALL ON videoclubbd.* TO 'spq'@'localhost';"

script:
 - mvn clean compile
 - mvn datanucleus:schema-create 
 - mvn test
 
branches:
  only:
  - master

notifications:
  email:
    recipients:
      - sergi.lopez@opendeusto.es
      
    on_success: never
    on_failure: always
