language: java

services:
  - mysql

before_script:  
  - cd videoClub
  - mysql -u root -e 'CREATE DATABASE videoclubd;'
  - mysql -u root -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'root';"
  - mysql -u root -e "GRANT ALL ON videoclubbd.* TO 'root'@'localhost';"
